language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run build

script: echo 'skip test' # Skip `yarn test`

deploy:
  target_branch: master
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: dev

notifications:
  email:
    on_failure: always

branches:
  only:
    - dev
